networks:
  main-network:
    driver: bridge

services:
  node:
    image: node:20-alpine
    container_name: node_dev
    working_dir: /app
    volumes:
      - ./matcha:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - main-network