networks:
  main-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules:

services:

  matcha_nginx:
    container_name: matcha_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    stop_grace_period: 2s
    networks:
      - main-network
    restart: on-failure

  matcha_server:
    image: node:alpine
    container_name: matcha_server
    working_dir: /app
    volumes:
      - ./matcha:/app
      - node_modules:/app/node_modules
    expose:
      - "3000"
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
    networks:
      - main-network
    depends_on:
      matcha_postgres:
        condition: service_healthy
    restart: on-failure
  

  matcha_postgres:
    container_name: matcha_postgres
    image: postgres:17-alpine
    expose:
      - "5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - main-network
    ports: # for dev only, used by adminer
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d matcha -U alice"]
      interval: 1s
      timeout: 1s
      retries: 5
    restart: on-failure

  matcha_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main-network
    depends_on:
      matcha_postgres:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit
    container_name: matcha_mailpit
    ports:
      - "8025:8025"   # Interface web
      - "1025:1025"   # Serveur SMTP
    networks:
      - main-network