CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS earthdistance;

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),

  "first_name" varchar(50) NOT NULL
    CHECK (char_length(first_name) >= 2 AND first_name !~ $$[^A-Za-zÀ-ÖØ-öø-ÿ' -]$$),

  "last_name" varchar(50) NOT NULL
    CHECK (char_length(last_name) >= 2 AND last_name !~ $$[^A-Za-zÀ-ÖØ-öø-ÿ' -]$$),

  "email" varchar(255) UNIQUE NOT NULL
    CHECK (email ~ $$^[^@\s]+@[^@\s]+\.[^@\s]+$$),

  "passwd" varchar(255) NOT NULL,

  "birthdate" date NOT NULL
    CHECK (
      birthdate <= (current_date - interval '18 years') AND
      birthdate >= (current_date - interval '100 years')
    ),    

  "country" varchar(30)
    CHECK (country IS NULL OR country !~ $$[^A-Za-zÀ-ÖØ-öø-ÿ' -]$$),

  "city" varchar(50)
    CHECK (city IS NULL OR city !~ $$[^A-Za-zÀ-ÖØ-öø-ÿ' -]$$),

  "latitude" float CHECK (latitude BETWEEN -90 AND 90),
  "longitude" float CHECK (longitude BETWEEN -180 AND 180),

  "gender" char(1) CHECK (gender IN ('M', 'F')),
  "sex_pref" char(1) CHECK (sex_pref IN ('M', 'F', 'B')),

  "bio" text,
  "fame" float CHECK (fame >= 0),

  "is_verified" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE pictures (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "mime_type" varchar(10),
  "data" bytea NULL,
  "is_main" boolean DEFAULT false
);

-- Fonction that prevent to addd more that 5 pic
CREATE OR REPLACE FUNCTION check_max_pictures()
RETURNS trigger AS $$
BEGIN
  IF (SELECT COUNT(*) FROM pictures WHERE user_id = NEW.user_id) >= 5 THEN
    RAISE EXCEPTION 'Limite de 5 photos atteinte pour cet utilisateur';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- trigger that call check_max_pictures at every insertion
CREATE TRIGGER pictures_limit_trigger
BEFORE INSERT ON pictures
FOR EACH ROW
EXECUTE FUNCTION check_max_pictures();

CREATE TABLE "interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(80) UNIQUE NOT NULL
);

CREATE TABLE "user_interests" (
  "user_id" uuid NOT NULL,
  "interest_id" int NOT NULL
);

CREATE TABLE "matches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" uuid NOT NULL,
  "user2_id" uuid NOT NULL,
  "status" varchar NOT NULL DEFAULT 'like',
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "views" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "seen_by" uuid NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "chat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" uuid NOT NULL,
  "recipient_id" uuid NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);


CREATE TYPE notification_type AS ENUM ('like', "match", 'unlike', 'message');
CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "target_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "sender_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "message" text NOT NULL,
  "type" notification_type NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);




CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp),
  "expires_at" timestamp DEFAULT (current_timestamp + interval '7 days'),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);


CREATE TABLE "email_verifications" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp DEFAULT (current_timestamp + interval '1 days'),
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE VIEW "users_with_interests" AS
SELECT
  u.id,
  u.first_name,
  LEFT(u.last_name, 1) AS last_name,
  u.gender,
  u.city,
  u.latitude,
  u.longitude,
  u.bio,
  u.fame,
  u.sex_pref,
  date_part('year', age(current_date, u.birthdate))::int AS age,
  COALESCE(json_agg(i.name) FILTER (WHERE i.name IS NOT NULL), '[]') AS interests
FROM users u
LEFT JOIN user_interests ui ON u.id = ui.user_id
LEFT JOIN interests i ON ui.interest_id = i.id
GROUP BY u.id;

CREATE VIEW my_profile AS
SELECT
  u.id,
  u.first_name,
  u.last_name,
  u.email,
  u.gender,
  u.city,
  u.latitude,
  u.longitude,
  u.bio,
  u.sex_pref,
  date_part('year', age(current_date, u.birthdate))::int AS age,
  COALESCE(json_agg(i.name) FILTER (WHERE i.name IS NOT NULL), '[]') AS interests
FROM users u
LEFT JOIN user_interests ui ON u.id = ui.user_id
LEFT JOIN interests i ON ui.interest_id = i.id
GROUP BY u.id;

CREATE VIEW users_me_like AS
SELECT m.user1_id AS me, uwi.*
FROM matches m
JOIN users_with_interests uwi ON uwi.id = m.user2_id
WHERE m.status = 'like';

CREATE VIEW users_who_like_me AS
SELECT m.user2_id AS me, uwi.*
FROM matches m
JOIN users_with_interests uwi ON uwi.id = m.user1_id
WHERE m.status = 'like';

CREATE OR REPLACE FUNCTION compatible_users_from(
  ref_user_id UUID
)
RETURNS TABLE (
  id UUID,
  first_name TEXT,
  last_name TEXT,
  gender TEXT,
  city TEXT,
  bio TEXT,
  age INT,
  interests JSON,
  fame INT,
  distance INT
)
AS $$
  SELECT
    u.id,
    u.first_name,
    u.last_name,
    u.gender,
    u.city,
    u.bio,
    u.age,
    u.interests,
    u.fame,
    ceil(
      earth_distance(
        ll_to_earth(me.latitude, me.longitude),
        ll_to_earth(u.latitude, u.longitude)
      ) / 1000
    )::int AS distance
  FROM users_with_interests u
  JOIN users me ON me.id = ref_user_id
  WHERE
    u.id <> me.id
    AND (
      me.sex_pref = 'B' OR me.sex_pref = u.gender
    )
    AND (
      u.sex_pref = 'B' OR u.sex_pref = me.gender
    )
    AND NOT EXISTS (
      SELECT 1
      FROM matches m
      WHERE
        (
          (m.user1_id = ref_user_id AND m.user2_id = u.id)
          OR
          (m.user1_id = u.id AND m.user2_id = ref_user_id)
        )
        AND m.status = 'block'
    );
$$ LANGUAGE sql STABLE;






CREATE INDEX ON "sessions" ("user_id");

CREATE UNIQUE INDEX ON "user_interests" ("user_id", "interest_id");

CREATE UNIQUE INDEX ON "matches" ("user1_id", "user2_id");

CREATE UNIQUE INDEX ON "views" ("user_id", "seen_by");

CREATE UNIQUE INDEX unique_main_picture_per_user
ON pictures (user_id)
WHERE is_main = true;

ALTER TABLE "pictures" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "views" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "views" ADD FOREIGN KEY ("seen_by") REFERENCES "users" ("id");

ALTER TABLE "chat" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "chat" ADD FOREIGN KEY ("recipient_id") REFERENCES "users" ("id");
