CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "passwd" varchar(255) NOT NULL,
  "country" varchar(30) NOT NULL DEFAULT 'France',
  "city" varchar(50),
  "latitude" float,
  "longitude" float,
  "gender" char(1) NOT NULL,
  "sex_pref" char(1) NOT NULL DEFAULT 'B',
  "bio" text,
  "fame" float,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE pictures (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "url" text NULL,
  "mime_type" varchar(10),
  "data" bytea NULL,
  CHECK (
    (url IS NOT NULL AND data IS NULL) OR 
    (url IS NULL AND data IS NOT NULL)
  )
);

CREATE TABLE "interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(80) UNIQUE NOT NULL
);

CREATE TABLE "user_interests" (
  "user_id" uuid NOT NULL,
  "interest_id" int NOT NULL
);

CREATE TABLE "matches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" uuid NOT NULL,
  "user2_id" uuid NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending',
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "views" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" uuid NOT NULL,
  "user2_id" uuid NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "chat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" uuid NOT NULL,
  "recipient_id" uuid NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE UNIQUE INDEX ON "user_interests" ("user_id", "interest_id");

CREATE UNIQUE INDEX ON "matches" ("user1_id", "user2_id");

CREATE UNIQUE INDEX ON "views" ("user1_id", "user2_id");

ALTER TABLE "pictures" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "views" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "views" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "chat" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "chat" ADD FOREIGN KEY ("recipient_id") REFERENCES "users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
