CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS earthdistance;

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "passwd" varchar(255) NOT NULL,
  "country" varchar(30) NOT NULL DEFAULT 'France',
  "city" varchar(50),
  "latitude" float,
  "longitude" float,
  "birthdate" DATE NOT NULL,
  "gender" char(1) NOT NULL,
  "sex_pref" char(1) NOT NULL DEFAULT 'B',
  "bio" text,
  "fame" float,
  "is_verified" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE pictures (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "mime_type" varchar(10),
  "data" bytea NULL,
  "is_main" boolean DEFAULT false
);

CREATE TABLE "interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(80) UNIQUE NOT NULL
);

CREATE TABLE "user_interests" (
  "user_id" uuid NOT NULL,
  "interest_id" int NOT NULL
);

CREATE TABLE "matches" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" uuid NOT NULL,
  "user2_id" uuid NOT NULL,
  "status" varchar NOT NULL DEFAULT 'like',
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "views" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user1_id" uuid NOT NULL,
  "user2_id" uuid NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "chat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" uuid NOT NULL,
  "recipient_id" uuid NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp),
  "expires_at" timestamp DEFAULT (current_timestamp + interval '7 days'),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);


CREATE TABLE "email_verifications" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp DEFAULT (current_timestamp + interval '1 days'),
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE VIEW "users_with_interests" AS
SELECT
  u.id,
  u.username,
  u.gender,
  u.city,
  u.latitude,
  u.longitude,
  u.bio,
  u.sex_pref,
  date_part('year', age(current_date, u.birthdate))::int AS age,
  COALESCE(json_agg(i.name) FILTER (WHERE i.name IS NOT NULL), '[]') AS interests
FROM users u
LEFT JOIN user_interests ui ON u.id = ui.user_id
LEFT JOIN interests i ON ui.interest_id = i.id
GROUP BY u.id;

CREATE VIEW my_profile AS
SELECT
  u.id,
  u.username,
  u.email,
  u.gender,
  u.city,
  u.latitude,
  u.longitude,
  u.bio,
  u.sex_pref,
  date_part('year', age(current_date, u.birthdate))::int AS age,
  COALESCE(json_agg(i.name) FILTER (WHERE i.name IS NOT NULL), '[]') AS interests
FROM users u
LEFT JOIN user_interests ui ON u.id = ui.user_id
LEFT JOIN interests i ON ui.interest_id = i.id
GROUP BY u.id, u.username, u.email, u.gender, u.city, u.latitude, u.longitude, u.bio, u.sex_pref, u.birthdate;

CREATE VIEW users_me_like AS
SELECT m.user1_id AS me, uwi.*
FROM matches m
JOIN users_with_interests uwi ON uwi.id = m.user2_id
WHERE m.status = 'like';

CREATE VIEW users_who_like_me AS
SELECT m.user2_id AS me, uwi.*
FROM matches m
JOIN users_with_interests uwi ON uwi.id = m.user1_id
WHERE m.status = 'like';

CREATE INDEX ON "sessions" ("user_id");

CREATE UNIQUE INDEX ON "user_interests" ("user_id", "interest_id");

CREATE UNIQUE INDEX ON "matches" ("user1_id", "user2_id");

CREATE UNIQUE INDEX ON "views" ("user1_id", "user2_id");

ALTER TABLE "pictures" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "views" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("id");

ALTER TABLE "views" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("id");

ALTER TABLE "chat" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "chat" ADD FOREIGN KEY ("recipient_id") REFERENCES "users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
