INSERT INTO interests (name) VALUES
('Hiking'),
('Cooking'),
('Photography'),
('Yoga'),
('Reading'),
('Traveling'),
('Painting'),
('Video Games'),
('Gardening'),
('Music Production'),
('Rock Climbing'),
('Wine Tasting'),
('Podcasts'),
('Dancing'),
('Surfing'),
('Anarchy'),
('Board Games'),
('Meditation'),
('Craft Beer'),
('Stand-up Comedy'),
('Astronomy'),
('Baking'),
('Museum Hopping'),
('Creative Writing'),
('Politics'),
('Pottery'),
('Film Photography'),
('Coffee Connoisseur'),
('Animal Volunteering'),
('Scuba Diving'),
('Chess'),
('Mixology'),
('Minimalism'),
('Vinyl Record Collecting'),
('Learning New Languages'),
('Interior Design'),
('Weightlifting'),
('Vintage Thrifting'),
('Bird Watching'),
('Home DIY Projects'),
('Karaoke'),
('Snowboarding'),
('Spoken Word Poetry'),
('Food Blogging'),
('Astrophotography'),
('Salsa Dancing'),
('Skateboarding'),
('Minimalist Living'),
('Software Development'),
('Classic Car Restoration'),
('Farmers Markets'),
('Paddleboarding'),
('Journaling'),
('Cocktail Crafting'),
('Bouldering'),
('Documentary Films'),
('Punk Rock'),
('Urban Gardening'),
('Motorcycle Touring'),
('Urbex'),
('Street Fashion'),
('Kayaking'),
('Songwriting'),
('Brunch Culture'),
('Mountain Biking'),
('Modern Calligraphy'),
('Graphic Novels'),
('Japanese Tea Ceremony'),
('Wilderness Camping'),
('Fashion Design'),
('Virtual Reality Gaming'),
('Activism'),
('Stoic Philosophy'),
('International Street Food'),
('Backcountry Skiing'),
('Digital Illustration'),
('Horror Book Club'),
('Fermenting Foods'),
('Paragliding'),
('Close-up Magic'),
('Antique Restoration'),
('Tattoo Artistry'),
('Renaissance History'),
('Craft Beer Brewing'),
('Acroyoga'),
('Blockchain Technology'),
('Bonsai Cultivation'),
('Paranormal Investigation'),
('Historical Fencing'),
('Zero-Waste Lifestyle'),
('Electronic Music Production'),
('Geocaching'),
('Astrology & Tarot'),
('Kiteboarding'),
('Woodworking'),
('Independent Filmmaking'),
('Wildlife Photography'),
('Learning Piano'),
('Historical Reenactment'),
('Class Struggle');