// matcha/src/lib/db/users.ts
import {  pool } from './db-utils';
import bcrypt from 'bcryptjs';
import { executeQuery } from "./db-utils";

export interface User {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  passwd: string;
  country?: string;
  city?: string;
  latitude?: number;
  longitude?: number;
  birthdate: string;
  gender?: string;
  sex_pref?: string;
  bio?: string;
  fame?: number;
  created_at?: Date;
}

/**
 * Create a new user
 * Omit allows to not pass given args that will be generated by de DB
 * the synthax with values placeholder come from pg 
 */
export async function createUser(user: Omit<User, 'id' | 'created_at'>): Promise<User> {
  const query = {
    text: `
      INSERT INTO users (first_name, last_name, email, passwd, country, city, latitude, longitude, birthdate, gender, sex_pref, bio, fame)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12, $13)
      RETURNING *;
    `,
    values: [
      user.first_name,
      user.last_name,
      user.email,
      user.passwd,
      user.country ?? null,
      user.city ?? null,
      user.latitude ?? null,
      user.longitude ?? null,
      user.birthdate,
      user.gender ?? null,
      user.sex_pref ?? null,
      user.bio ?? null,
      user.fame ?? 0
    ]
  };

  const result = await pool.query<User>(query);
  return result.rows[0];
}

/**
 * Get user by id
 */
export async function getUserById(id: string): Promise<User | null> {
  const result = await pool.query<User>(
    'SELECT * FROM users WHERE id = $1',
    [id]
  );
  return result.rows[0] ?? null;
}

/**
 * Get user by email
 */
export async function getUserByEmail(email: string): Promise<User | null> {
  const result = await pool.query<User>(
    'SELECT * FROM users WHERE email = $1',
    [email]
  );
  return result.rows[0] ?? null;
}

/**
 * List all users
 */
export async function listUsers(): Promise<User[]> {
  const result = await pool.query<User>('SELECT * FROM users ORDER BY created_at DESC');
  return result.rows;
}

/**
 * Try to log user
 */
export async function loginUser(email: string, password: string): Promise<User | null> {
  const result = await pool.query<User>(
    'SELECT * FROM users WHERE email=$1',
    [email]
  );
  const user = result.rows[0];
  if (!user) return null;

  const match = await bcrypt.compare(password, user.passwd);
  if (!match) return null;

  return user;
}


/**
 * Fetch total number of pages based on PROFILES_LIMIT
 */
export async function fetchTotalPages(): Promise<number> {
  const min_users: number = parseInt(process.env.PROFILES_LIMIT ?? "20");
  const result = await pool.query<{total : string}>('SELECT count(*) AS total FROM users');
  const totalUsers = parseInt(result.rows[0].total, 10);
  return Math.ceil(totalUsers / min_users);
}

/**
 * Update a user (partial update)
 */
export async function updateUser(
  id: string,
  updates: Partial<User>
): Promise<User | null> {
  // Liste blanche des champs qu’un utilisateur peut modifier
  const allowedFields: (keyof User)[] = [
    "first_name",
    "last_name",
    "email",
    "city",
    "country",
    "gender",
    "sex_pref",
    "bio",
    "birthdate",
    "latitude",
    "longitude"
  ];

  const fields = Object.keys(updates).filter((field) =>
    allowedFields.includes(field as keyof User)
  );

  if (fields.length === 0) {
    return await getUserById(id);
  }

  const setClauses = fields
    .map((field, i) => `"${field}" = $${i + 1}`)
    .join(", ");
  const values = fields.map((field) => (updates as any)[field]);

  const query = {
    text: `UPDATE users SET ${setClauses} WHERE id = $${
      fields.length + 1
    } RETURNING *`,
    values: [...values, id],
  };

  const result = await pool.query<User>(query);
  return result.rows[0] ?? null;
}
/**
 * Delete a user
 */
export async function deleteUser(id: string): Promise<boolean> {
  const result = await pool.query('DELETE FROM users WHERE id = $1', [id]);
  return (result.rowCount ?? 0) > 0;
}

export async function markUserAsVerified(userId: string): Promise<boolean> {
  const query = `
    UPDATE users
    SET is_verified = true
    WHERE id = $1
  `;
  const result = await executeQuery(query, [userId]);
  return (result.rowCount ?? 0) > 0;
}